### ISSUE TITLE
Document establishing a new top level DNS domain

### ISSUE THREAD

**Issue by JJediny** [18F/dns#363]
## User Story
As a new TTS member I want a clear guide on the entire workflow for creating a new top-level `*.gov` domain. 

## Details
Documentation gaps exist for new users who need to establish an entirely new top-level `*.gov` domain. Documentation is unclear that the first step is to make a PR and merge to obtain the output from nameservers to then submit for the dotgov.gov registration form.

## Acceptance Criteria 
- [ ] Documentation update covers the following:
   - [ ] Request new domain in dotgov.gov (submit form w/ Program POC @self, admin POC @afeld, and billing POC @JJediny)
   - [ ] Explains how https://github.com/18F/dns/blob/master/get_zone.py works
   - [ ] Steps in sequence order start to finish

Include secondary considerations/checks for a new domain
   - [ ] Coordinate with SecOps (Armando Quintananieves) on DMARC 
   - [ ] Add domain to HSTS preloading list

**Comment by afeld** [comment]
- Coordinate with SecOps (Armando Quintananieves) on DMARC
- Add to HSTS preloading list

**Comment by its-a-lisa** [comment]
Closing based on the decision made on 4/21/20 to close anything that wasn't a Major current Initiative or Notable mention from the [Tech Portfolio Sprint Planning 2020-04-20](https://docs.google.com/document/d/1Q4XRL47tCva3PrIBa5WVcPAtYwv8nFgnyNH6RelnsFc/edit) radiated intent in [slack](https://gsa-tts.slack.com/archives/CNW3GL70S/p1587578121241100) and open for discussion on reopening.
